apiVersion: apps/v1
kind: Deployment
metadata:
  name: adworks-api
  labels:
    app: adworks-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adworks-api
  template:
    metadata:
      labels:
        app: adworks-api
    spec:
      containers:
      - name: adworks-api
        image: eworkspace/adworks-api:latest
        imagePullPolicy: Always
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "Instance__Id"
          value: "$(MY_POD_NAME)"
        - name: ENABLE_SAMBA
          value: "0"
        - name: ASPNETCORE_ENVIRONMENT
          value: dev
        - name: "LogFile"
          value: "files/logs-$(MY_POD_NAME)/api.log"
        - name: "ConnectionStrings__DefaultConnection"
          value: "Server=adworks-mysql;Port=3306;Database=adworks;UserId=adworks_user;Password=E0aQ63o7lU;"
        - name: "MessageQueueSettings__HostName"
          value: "adworks-mq-rabbitmq-ha"
        - name: "MessageQueueSettings__UserName"
          value: "adworks-media-web-api"
        - name: "MessageQueueSettings__Password"
          value: "biezoh0Zeen3tie9mux6omuw"
        - name: "MessageQueueSettings__Port"
          value: "5671"
        - name: "MessageQueueSettings__Ssl"
          value: "true"
        - name: "MessageQueueSettings__VirtualHost"
          value: "/prod"
        - name: "BaseAssetFolder"
          value: "/mnt"
        - name: "FFMpeg__ToolPath"
          value: "FFMpeg/linux"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: data
          mountPath: /mnt
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: adworks-dev-shared
---
apiVersion: v1
kind: Service
metadata:
  name: adworks-api
spec:
  selector:
    app: adworks-api
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  sessionAffinity: ClientIP
  type: ClusterIP
