version: '3.8'
services:
  webapi:
    image: eworkspace/adworks-api:latest
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=prod
      - ASPNETCORE_URLS=http://+:5000
  proxy:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    links:
      - webapi