pipeline {
  agent any

  environment {
    registry = 'eworkspace/adworks-dashboard'
    registryCredential = 'dockerhub'
  }

  stages {
    stage('Checkout') {
      steps {
        git credentialsId: 'github-ssh-jeffjin', url: 'git@github.com:JeffJin/nx-eworks.git', branch: 'develop'
      }
    }
    stage('Stop current running image and remove') {
      steps{
         sh """
           docker ps -a \
           | grep $registry \
           | awk '{ print \$1 }' \
           | xargs -I {} docker stop {} \
           """
        sh """
           docker ps -a \
           | grep $registry \
           | awk '{ print \$1 }' \
           | xargs -I {} docker rm -f {} \
           """
        sh """
           docker images \
           | grep $registry \
           | awk '{ print \$3 }' \
           | xargs -I {} docker rmi -f {} \
           """
      }
    }
    stage('Build Angular App Image') {
      steps {
        sh "docker build -t $registry:$BUILD_NUMBER ."
        sh "docker tag $registry:$BUILD_NUMBER $registry:latest"
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( "", "dockerhub" ) {
            sh "docker push $registry:$BUILD_NUMBER"
            sh "docker push $registry:latest"
          }
        }
      }
    }
    stage('Run Adworks-Dashboard Angular App docker image') {
      steps{
        script {
          docker.withRegistry( "", "dockerhub" ) {
            sh "docker run -d -p 8333:80 --name adworks-dashboard $registry:latest"
          }
        }
      }
    }
  }
}
